---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic
  name: petclinic
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 80
      targetPort: 8080
      #nodePort: 30880
  selector:
    app: petclinic


